language: node_js

addons:
  sonarcloud:
    organization: "tanayseven"
    token:
      secure: "G+fa6uNsvtaEG1Wc/xq75JKSp6evRk2xC7utOIAS4rEM93hrW+lYZJI59SVUfjZVk7KW1XfSN+mlP/z/RG+B5rHx8WJYC4/3JPKfQ0lpkLlRJ81j1APA4BC2AwQxNTRRnMHVZw9RbZuwSSh8lj3JPLnJvvrIk5sl90QBAiJv1pqKtGwwEEvDisgBTFH323qE1mZh5cmrW66rBTIqJ++JHI09hwvz6PAkszv/qdTJMBn8x/d69ipS1ZBvJ7AiBW7816C7yj5ZKsGSdQ+gL3U1+vN5qP5xjiiOeastkZWRRcCoJjuzb4Il6uFAwkELGq+m/0uyCroHhOwlPwKD8c6W1o6fABzUqpVfpK5Aw2aejHWBDKH64H2tfwGzBEZ6n4d4IKGwLTFJmV5FBAZ3QLMnfclpUhRFYfzOTXXT7efZxy0MOSlafpIQJCwft8AGlMmusOBw8IC+MN/DUaK3XU8nKT8SNqXO61qbmIg1ZjjzYZKvyOdWS9kEcAM757eXju7xptq7J2zbLN4VC9Nf2AOO+dJ/nrMFgbIjoicH1mAt4PpNJ91lO3dCq8f/TMyflsUFqH7+HNLMJuGWJP1Zh9w5HYTg3+MXRR/RQ01CXvWsAwOCpOG8dkSDtgB7sSL9HsC943eeP8PDzDmGf3Nk4hOs+4gn4IV63Qm7HO92ASYiwUs="

node_js:
  - 10.16

env:
  - CI=true

script: 
  - npm run lint
  - npm test -- --coverage
  - sonar-scanner
